In [1]:
import erppeek
import pandas as pd

In [2]:
USERNAME = "admin"
PASSWORD = "admin"
DB = "doc-approval"
SERVER = "http://localhost:8069"

client = erppeek.Client(SERVER, db=DB, user=USERNAME, password=PASSWORD)
client

In [3]:
client.search('res.users', [])

[2, 23]

In [3]:
df_employee = pd.read_excel('udin.lecturer.lecturer.xls')
df_employee.fillna("", inplace=True)
df_employee

,name,Gelar depan,Gelar belakang,Tmp Lahir,Jenis kelamin,Marital Status,NPP,Status Kepegawaian,Status Aktif,Email
0,Abdul Syukur,Dr.,,KOTA SEMARANG,1,2,0686.11.1992.017,11,1,abdul.syukur@dsn.dinus.ac.id
1,Heru Agus Santoso,,Ph.D,KOTA TEGAL,1,2,0686.11.1998.165,11,1,heru.agus.santoso@dsn.dinus.ac.id
2,ENNY SUSILOWATI M,,"SKM, M.Kom, Ph.D",KOTA SEMARANG,2,2,0686.11.2000.219,11,1,enny.rachmani@dsn.dinus.ac.id
3,Raden Arief Nugroho,Dr.,"S.S., M.Hum.",KAB. TEMANGGUNG,1,2,0686.11.2010.367,11,1,arief.nugroho@dsn.dinus.ac.id
4,Vincent Didiek Wiet Aryanto,Prof.,"MBA, Ph.D",SURAKARTA,1,2,0686.11.2014.606,11,1,vincent.didiek.wiet.aryanto@dsn.dinus.ac.id

In [4]:
df_department = pd.read_excel('hr.department 1.xls')
df_department.fillna("", inplace=True)
df_department

,Sekup Kerja,Manajer/Nama & Gelar,Singkatan,Nama Inggris,Kode Fakultas
0,Fakultas,"Prof. Vincent Didiek Wiet Aryanto, MBA, Ph.D",FEB,Economics and Business,B
1,Fakultas,"Dr. Raden Arief Nugroho, S.S., M.Hum.",FIB,Humanities,C
2,Fakultas,Dr. Abdul Syukur,FIK,Computer Science,A
3,Fakultas,"Enny Rachmani, SKM, M.Kom, Ph.D",FKes,Health Science,D
4,Fakultas,"Heru Agus Santoso, Ph.D",FT,Engineering,E

In [6]:
client.search("docav.department", [])

[]

In [7]:
erppeek.Model(client, "docav.department").keys()

['__last_update',
 'active',
 'child_ids',
 'color',
 'company_id',
 'complete_name',
 'create_date',
 'create_uid',
 'display_name',
 'email',
 'fax',
 'has_message',
 'id',
 'jobs_ids',
 'kode_fakultas',
 'manager_id',
 'master_department_id',
 'member_ids',
 'message_attachment_count',
 'message_follower_ids',
 'message_has_error',
 'message_has_error_counter',
 'message_has_sms_error',
 'message_ids',
 'message_is_follower',
 'message_main_attachment_id',
 'message_needaction',
 'message_needaction_counter',
 'message_partner_ids',
 'misi',
 'misi_inggris',
 'nama_inggris',
 'name',
 'note',
 'parent_id',
 'parent_path',
 'phone',
 'plan_ids',
 'plans_count',
 'sambutan_inggris',
 'sambutan_ketua',
 'sekretaris',
 'singkatan',
 'tipe_unit',
 'total_employee',
 'visi',
 'visi_inggirs',
 'write_date',
 'write_uid']

In [5]:
tipe_unit_list = [('0', 'Universitas'), ('1','Fakultas'),('2','Jurusan'), ('3','Prodi'),('4','Laboratorium'),('5','UPT'),('6','Penyelenggara MKU'),('7', 'Ormawa')]

for i, depart in df_department.iterrows():
    if(client.search('docav.department', [("nama_inggris", "=", depart["Nama Inggris"])])):
        continue
    print(depart["Nama Inggris"])
    search_tipe = [item for item in tipe_unit_list if item[1] ==  depart["Sekup Kerja"]]
    values = {
        'tipe_unit': search_tipe[0][0],
        'name': depart["Nama Inggris"],
        'nama_inggris': depart["Nama Inggris"],
        'singkatan': depart["Singkatan"]
    }
    client.create("docav.department", values)

Economics and Business
Humanities
Computer Science
Health Science
Engineering

In [12]:
erppeek.Model(client, "docav.pegawai").keys()

['__last_update',
 'active',
 'activity_date_deadline',
 'activity_exception_decoration',
 'activity_exception_icon',
 'activity_ids',
 'activity_state',
 'activity_summary',
 'activity_type_icon',
 'activity_type_id',
 'activity_user_id',
 'additional_note',
 'address_home_id',
 'address_id',
 'aktif',
 'avatar_1024',
 'avatar_128',
 'avatar_1920',
 'avatar_256',
 'avatar_512',
 'bank_account_id',
 'barcode',
 'birthday',
 'bpjs',
 'category_ids',
 'certificate',
 'child_all_count',
 'child_ids',
 'children',
 'coach_id',
 'color',
 'company_country_code',
 'company_country_id',
 'company_id',
 'country_id',
 'country_of_birth',
 'create_date',
 'create_uid',
 'currency_id',
 'department_id',
 'departure_date',
 'departure_description',
 'departure_reason_id',
 'display_name',
 'driving_license',
 'email',
 'emergency_contact',
 'emergency_phone',
 'employee_type',
 'full_name',
 'gelar_belakang',
 'gelar_depan',
 'gender',
 'golongan_darah',
 'has_message',
 'has_work_permit',
 'hr_icon_display',
 'hr_presence_state',
 'id',
 'id_card',
 'id_siakad',
 'identification_id',
 'image_1024',
 'image_128',
 'image_1920',
 'image_256',
 'image_512',
 'is_address_home_a_company',
 'job_id',
 'job_title',
 'kecamatan',
 'km_home_work',
 'lang',
 'last_activity',
 'last_activity_time',
 'marital',
 'marital_status',
 'member_of_department',
 'message_attachment_count',
 'message_follower_ids',
 'message_has_error',
 'message_has_error_counter',
 'message_has_sms_error',
 'message_ids',
 'message_is_follower',
 'message_main_attachment_id',
 'message_needaction',
 'message_needaction_counter',
 'message_partner_ids',
 'mobile',
 'mobile_phone',
 'my_activity_date_deadline',
 'name',
 'nik',
 'no_dplk',
 'no_kk',
 'no_sk_awal',
 'notes',
 'npp',
 'npwp',
 'parent_id',
 'passport_id',
 'permit_no',
 'phone',
 'pin',
 'place_of_birth',
 'private_email',
 'punya_user',
 'rekening_bni',
 'rekening_bpd',
 'related_contact_ids',
 'related_contacts_count',
 'resource_calendar_id',
 'resource_id',
 'scope_kerja',
 'show_hr_icon_display',
 'sinid',
 'spouse_birthdate',
 'spouse_complete_name',
 'ssnid',
 'status_kepegawaian',
 'status_terakhir',
 'structural',
 'study_field',
 'study_school',
 'subordinate_ids',
 'tanggal_lahir',
 'tanggal_sk_awal',
 'tempat_lahir',
 'tz',
 'user_id',
 'user_partner_id',
 'visa_expire',
 'visa_no',
 'work_contact_id',
 'work_email',
 'work_location_id',
 'work_permit_expiration_date',
 'work_permit_name',
 'work_permit_scheduled_activity',
 'work_phone',
 'write_date',
 'write_uid']

In [12]:
df_employee.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   name                5 non-null      object
 1   Gelar depan         5 non-null      object
 2   Gelar belakang      5 non-null      object
 3   Tmp Lahir           5 non-null      object
 4   Jenis kelamin       5 non-null      int64
 5   Marital Status      5 non-null      int64
 6   NPP                 5 non-null      object
 7   Status Kepegawaian  5 non-null      int64
 8   Status Aktif        5 non-null      int64
 9   Email               5 non-null      object
dtypes: int64(4), object(6)
memory usage: 532.0+ bytes

In [7]:

for i, employee in df_employee.iterrows():
    check = client.search("docav.pegawai", [("name","=",employee["name"])])
    if len(check) > 0:
        continue
    resource = client.create('resource.resource',{'name': employee["name"]})
    values = {
        'name': employee["name"],
        'gelar_depan': employee["Gelar depan"],
        'gelar_belakang': employee["Gelar belakang"],
        'tempat_lahir': employee["Tmp Lahir"],
        'gender': str(employee["Jenis kelamin"]),
        'marital_status': str(employee["Marital Status"]),
        'npp': employee["NPP"],
        'status_kepegawaian': str(employee["Status Kepegawaian"]),
        'status_terakhir':str( employee["Status Aktif"]),
        'email': employee["Email"],
        "structural": str(5),
        'resource_id': resource
    }
    client.create("docav.pegawai", values)
    print(values)

{'name': 'Abdul Syukur', 'gelar_depan': 'Dr.', 'gelar_belakang': '', 'tempat_lahir': 'KOTA SEMARANG', 'gender': '1', 'marital_status': '2', 'npp': '0686.11.1992.017', 'status_kepegawaian': '11', 'status_terakhir': '1', 'email': 'abdul.syukur@dsn.dinus.ac.id', 'structural': '5', 'resource_id': 75}
{'name': 'Heru Agus Santoso', 'gelar_depan': '', 'gelar_belakang': 'Ph.D', 'tempat_lahir': 'KOTA TEGAL', 'gender': '1', 'marital_status': '2', 'npp': '0686.11.1998.165', 'status_kepegawaian': '11', 'status_terakhir': '1', 'email': 'heru.agus.santoso@dsn.dinus.ac.id', 'structural': '5', 'resource_id': 77}
{'name': 'ENNY SUSILOWATI M', 'gelar_depan': '', 'gelar_belakang': 'SKM, M.Kom, Ph.D', 'tempat_lahir': 'KOTA SEMARANG', 'gender': '2', 'marital_status': '2', 'npp': '0686.11.2000.219', 'status_kepegawaian': '11', 'status_terakhir': '1', 'email': 'enny.rachmani@dsn.dinus.ac.id', 'structural': '5', 'resource_id': 79}
{'name': 'Raden Arief Nugroho', 'gelar_depan': 'Dr.', 'gelar_belakang': 'S.S., M.Hum.', 'tempat_lahir': 'KAB. TEMANGGUNG', 'gender': '1', 'marital_status': '2', 'npp': '0686.11.2010.367', 'status_kepegawaian': '11', 'status_terakhir': '1', 'email': 'arief.nugroho@dsn.dinus.ac.id', 'structural': '5', 'resource_id': 81}
{'name': 'Vincent Didiek Wiet Aryanto', 'gelar_depan': 'Prof.', 'gelar_belakang': 'MBA, Ph.D', 'tempat_lahir': 'SURAKARTA', 'gender': '1', 'marital_status': '2', 'npp': '0686.11.2014.606', 'status_kepegawaian': '11', 'status_terakhir': '1', 'email': 'vincent.didiek.wiet.aryanto@dsn.dinus.ac.id', 'structural': '5', 'resource_id': 83}